/* agent/dashboard.js - GENERATES THE VISUAL MARKET INTERFACE */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DATA_FILE = path.join(__dirname, 'predictions.json');
const OUTPUT_FILE = path.join(__dirname, '../market_dashboard.html');

console.log("🔮 GENERATING ORACLE INTERFACE...");

// 1. Load Data
let predictions = [];
try {
    const raw = fs.readFileSync(DATA_FILE, 'utf8');
    predictions = JSON.parse(raw);
} catch (e) { console.log("No data found."); }

// 2. Calculate Stats
const total = predictions.length;
const resolved = predictions.filter(p => p.status === "RESOLVED");
const wins = resolved.filter(p => p.outcome === "WIN").length;
const accuracy = total > 0 ? Math.round((wins / resolved.length) * 100) || 0 : 0;
const active = predictions.filter(p => p.status === "ACTIVE");

// 3. Generate HTML
const html = `
<!DOCTYPE html>
<html>
<head>
    <title>PINKERTAPE ORACLE</title>
    <style>
        body { background: #0a0a0a; color: #00ff9d; font-family: 'Courier New', monospace; padding: 40px; }
        h1 { font-size: 3em; border-bottom: 2px solid #00ff9d; padding-bottom: 10px; text-transform: uppercase; }
        .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 40px; }
        .card { border: 1px solid #333; padding: 20px; background: #111; }
        .card h2 { margin: 0; font-size: 0.8em; color: #666; }
        .card .val { font-size: 2.5em; font-weight: bold; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { text-align: left; border-bottom: 1px solid #333; padding: 10px; color: #666; }
        td { border-bottom: 1px solid #222; padding: 15px 10px; }
        
        .badge { padding: 5px 10px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }
        .ACTIVE { background: #0044ff; color: white; }
        .WIN { background: #00ff9d; color: black; }
        .LOSS { background: #ff0055; color: white; }
        
        .risk-HIGH { color: #ff0055; }
        .risk-MEDIUM { color: #ffaa00; }
        
        .pulse { animation: pulse 2s infinite; }
        @keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.5; } 100% { opacity: 1; } }
    </style>
</head>
<body>

    <h1><span class="pulse">🔴</span> PinkerTape Prediction Market</h1>

    <div class="stats-grid">
        <div class="card">
            <h2>AI ACCURACY (30D)</h2>
            <div class="val">${accuracy}%</div>
        </div>
        <div class="card">
            <h2>TOTAL PREDICTIONS</h2>
            <div class="val">${total}</div>
        </div>
        <div class="card">
            <h2>ACTIVE MARKETS</h2>
            <div class="val" style="color:#0044ff">${active.length}</div>
        </div>
        <div class="card">
            <h2>ASSET TRACKED</h2>
            <div class="val">TRX</div>
        </div>
    </div>

    <h3>LIVE MARKET FEED</h3>
    <table>
        <thead>
            <tr>
                <th>STRIKE ID</th>
                <th>DATE</th>
                <th>TARGET</th>
                <th>CONFIDENCE</th>
                <th>SIGNALS (Whale/Mom)</th>
                <th>STATUS</th>
            </tr>
        </thead>
        <tbody>
            ${predictions.map(p => `
            <tr>
                <td>#${p.id}</td>
                <td>${p.date}</td>
                <td>$${p.strike} <span style="font-size:0.8em; opacity:0.7">(${p.direction})</span></td>
                <td class="risk-${p.confidence}">${p.confidence} (${p.probability}%)</td>
                <td>🐳 ${p.signals.whaleScore} / 📈 ${p.signals.momentum}</td>
                <td><span class="badge ${p.outcome || p.status}">${p.outcome || p.status}</span></td>
            </tr>
            `).reverse().join('')}
        </tbody>
    </table>

    <p style="margin-top:50px; color:#444; text-align:center">GENERATED BY AGENT GUARDIAN V2 // TRON NETWORK</p>

</body>
</html>
`;

fs.writeFileSync(OUTPUT_FILE, html);
console.log(`✅ Dashboard updated: ${OUTPUT_FILE}`);